# Generated by Django 4.2.8 on 2023-12-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggtart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggtart',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='post', verbose_name='이미지'),
        ),
    ]
